### ISSUE TITLE
Documentation improvement - How is tez faster?

### ISSUE THREAD

**Issue by swartchris8** [abhishekkrthakur/tez#1]
Great to see a nice Pytorch training library. 

I think it would help users use it maybe to show what kind of performance improvements come from the box with Tez. For example comparing how fp16 is enabled in tez vs vanilla pytorch could ben informative or just a quick list of optimisations that are easy to do with Tez such as fp16.

**Comment by abhishekkrthakur** [comment]
I'm working on improving documentation. Hopefully will be ready soon. tez.readthedocs.io

**Comment by swartchris8** [comment]
If there's any bits of the docs you'd like some feedback about I am happy to help

**Comment by hash-ir** [comment]
@abhishekkrthakur I could also help with the documentation bit

**Comment by Zhipeng-Ye** [comment]
hi, I use Tez for a quick start, it's a useful tool and it's really easy to use. I want to get more complex and useful usage, where I can find detailed documents. Hopefully, it will be ready soon.

**Comment by sounishnath003** [comment]
<img width="1206" alt="Screenshot 2022-06-04 at 12 27 47 PM" src="https://user-images.githubusercontent.com/40270033/171988510-0d5d8929-5578-468d-b549-c8b78d88bcbe.png">

Hi @abhishekkrthakur, I Started exploring Tez and its internals by building some models. I see one NOTE: is coming like this. How do I suppress and correct the Tez?Model inheritance.

Please come with a tutorial video on Tez and its components specifically. Thanks and Love from India.
