### ISSUE TITLE
Text classification examples - Tokenizer is defined twice

### ISSUE THREAD

**Issue by obesp** [abhishekkrthakur/tez#10]
The tokenizer is defined both in the model and the dataset in the BERT text classification examples.

multi_class.py, line 50:
`        self.tokenizer = transformers.BertTokenizer.from_pretrained(
            "bert-base-uncased", do_lower_case=True
        )`

**Comment by abhishekkrthakur** [comment]
Indeed it is. its not needed in model. seems like a copy-paste error. ;) i will fix it.
