### ISSUE TITLE
how to use multi gpu

### ISSUE THREAD

**Issue by zhangatao** [abhishekkrthakur/tez#12]
Hello, how to specify multiple GPUs during model fit?

**Comment by ingbeeedd** [comment]
method???

**Comment by abhishekkrthakur** [comment]
ill add multi gpu support this week

**Comment by Syavaprd** [comment]
> ill add multi gpu support this week

Hello, did you add it?

**Comment by Caizifen** [comment]
> ill add multi gpu support this week

@abhishekkrthakur Have you finished it? I think it is very useful and necessary to train with multiple GPUs.

**Comment by i-mein** [comment]
> ill add multi gpu support this week

@abhishekkrthakur any progress on that? 
or maybe some advice where we ned to modify to use nn.dataparallel()

**Comment by abhishekkrthakur** [comment]
its not as straight forward as i thought it was. anyways, the changes will require major api changes. thus, its better to do a new release with brand new api
