### ISSUE TITLE
Applying metrics after the epoch

### ISSUE THREAD

**Issue by waldcarl** [abhishekkrthakur/tez#30]
Dears, I am using tez to classify melanoma images (kaggle SIIM binary classification). With wtfml is possible to get AUC ~ 0.85. With tez, I am only getting AUC ~ 0.6. I saw that this happens, in tez, when using `metrics.roc_auc_score(...)` inside monitor_metrics method. This gives some ValueError exceptions, that must be handled returning auc = 0.5 (this error occurs when the data have only 1 class).

In the wtfml, the `metrics.roc_auc_score(...)` method is used only after Engine.evaluate. In this case, the data always have two classes (because the KStratified gives that).

I am wondering if it is possible, in tez, to apply the `metrics.roc_auc_score(...)` only after the epoch, and not in each `train_bs`. With that, the data always will have two classes, avoiding the ValueError exceptions.

PS. 

1. In the class definition __init__ I am using:
    `self.step_scheduler_after = "epoch"`
    `self.step_scheduler_metric = "valid_auc"`
2. In the monitor_metrics method:
    `try: auc = metrics.roc_auc_score(targets, outputs.ravel())`
    `except ValueError: auc = 0.5`
    `return {"auc": auc}`
3. My model.fit is defined as:
    `model.fit(train_dataset, valid_dataset=valid_dataset, train_bs=32, valid_bs=16,`
                   `device="cuda", epochs=50, callbacks=[es], fp16=False, n_jobs=2)`

**Comment by abhishekkrthakur** [comment]
You can do this by implementing your own custom callback. For example of a callback, take a look at EarlyStopping. You need to write something similar to that ;)

**Comment by waldcarl** [comment]
Thank you very much Abhishek.

As I needed the output (**out**) from the `self.model`, in order to apply the `roc_auc_score` as wtfml does, it was necessary to overload the `validate_one_step` method to return the loss, metrics, and **out**. With that, the `fit` method obtains the **out** (from the `validate_one_epoch` method) and use it to apply the `roc_auc_score`. In such case, the ROC obtained was ~0.87.

Both wtfml and tez are really good frameworks, each one with its benefits. Congrats for such amazing work !
