### ISSUE TITLE
AttributeError: module 'tez' has no attribute 'Model'

### ISSUE THREAD

**Issue by ar8372** [abhishekkrthakur/tez#37]

**Comment by abhishekkrthakur** [comment]
updating to 0.6.0 will fix this error. please note that tez.Model will be deprecated soon and will no longer be supported.

**Comment by ar8372** [comment]
If anyone having issue just first uninstall tez and then install 0.6.0 version.
```
pip uninstall tez
pip install -Iv tez==0.6.0
```
