### ISSUE TITLE
NotADirectortyerror

### ISSUE THREAD

**Issue by arjunsigdel94** [abhishekkrthakur/tez#4]
NotADirectoryError                        Traceback (most recent call last)
<ipython-input-19-a0be1c17c5b0> in <module>
----> 1 train_dataset[0]

/opt/conda/lib/python3.7/site-packages/tez/datasets/image_classification.py in __getitem__(self, item)
     39         targets = self.targets[item]
     40         if self.backend == "pil":
---> 41             image = Image.open(self.image_paths[item])
     42             if self.resize is not None:
     43                 image = image.resize(

/opt/conda/lib/python3.7/site-packages/PIL/Image.py in open(fp, mode, formats)
   2889 
   2890     if filename:
-> 2891         fp = builtins.open(filename, "rb")
   2892         exclusive_fp = True
   2893 

NotADirectoryError: [Errno 20] Not a directory: '../input/cassava-leaf-disease-classification/train.csv/1724663202.jpg'

**Comment by abhishekkrthakur** [comment]
Are you sure that `'../input/cassava-leaf-disease-classification/train.csv/1724663202.jpg'` path is correct? Doesnt look correct to me.
